stages:
  - build
  - test
  - deploy

release-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"

debug-test-coverage:
  image: "${CI_REGISTRY_IMAGE}:latest"
  stage: test
  script:
    - cd /opt
    - cmake -S . -B cmake-build-debug/ -D CMAKE_BUILD_TYPE=Debug
    - cmake --build cmake-build-debug/ --parallel 4
    - ctest --test-dir cmake-build-debug/ --output-on-failure --output-on-failure --parallel 4 -T Test -T Coverage
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
      codecov upload-process -t $CODECOV_TOKEN;
      fi

cmake-integration-test:
  image: "${CI_REGISTRY_IMAGE}:latest"
  stage: test
  script:
    - cd /opt/cmake/cmake_integration_test
    - cmake -S . -B cmake-build-release/ -D CMAKE_BUILD_TYPE=Release
    - cmake --build cmake-build-release/ --parallel 4
    - ./cmake-build-release/cmake_integration_test

pages:
  image: "${CI_REGISTRY_IMAGE}:latest"
  stage: deploy
  script:
    - poxy docs/poxy.toml
    - mv html/ public/
  artifacts:
    paths:
    - public
  only:
    - main