// Copyright (c) 2024 Viper Science LLC
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#ifndef _CARDANO_TSS_HPP_
#define _CARDANO_TSS_HPP_

// Standard library headers
#include <array>
#include <cstdint>
#include <span>
#include <stdexcept>
#include <utility>
#include <vector>

// Public libcardano Headers
#include <cardano/bip32_ed25519.hpp>
#include <cardano/secmem.hpp>

// For convenience:
using cardano::SecureByteArray;
using cardano::bip32_ed25519::PrivateKey;
using cardano::bip32_ed25519::PublicKey;
using cardano::bip32_ed25519::SEED_SIZE;
using cardano::bip32_ed25519::SIGNATURE_SIZE;

/// The Cardano TSS library namespace.
namespace cardano::tss
{

inline constexpr size_t NONCE_SIZE = 32;
inline constexpr size_t COMMITMENT_SIZE = 32;
inline constexpr size_t COEFFICIENT_SIZE = 32;

/// @brief Enum selector representing the key splitting algorithm options.
enum class KeySharingAlgorithm : std::uint8_t
{
    Direct,
    ShamirSecretSharing
};

/// @brief A threshold-signature key share.
/// @details A wrapper struct to represent a key share generated by a split. It
/// holds a key ID and Bip32-Ed25519 signing key. For Shamir Secret Sharing, the
/// key share represents {xi, f(xi)}. For direct key splitting the key ID is not
/// used.
struct KeyShare
{
    uint64_t id;
    PrivateKey key;

    /// @brief The publick key derived from the private key share.
    /// @return A Bip32-Ed25519 public key.
    auto publicKey() -> PublicKey { return this->key.publicKey(); }

    // TODO: Add serialize and deserialize methods.
};  // KeyShare

/// @brief Perform dealer functions for the threshold signature scheme.
/// @details Implement dealer functionality for the threshold operations such as
/// key splitting and signature combination. The implementation uses a simple
/// additive key sharing algorithm (direct key splitting) when the number of
/// keys shares (n) equals the required threshold (t) for a valid signature. For
/// the more general case (n >= t) where some subset of the key shares may be
/// combined to construct a valid signature, the Shamir Secret Sharing algorithm
/// is used. For more information see:
/// https://datatracker.ietf.org/doc/html/draft-hallambaker-threshold-sigs-06
/// @note Immutability is intended for this object.
class Dealer
{
  private:
    const uint32_t num_keys_;
    const uint32_t sig_threshold_;
    const KeySharingAlgorithm algorithm_;

    /// Validate the number of key shares input.
    static constexpr auto validateNumKeyShares(uint32_t n) -> uint32_t
    {
        if (n < 1)
        {
            throw std::invalid_argument("Invalid number of key shares.");
        }
        return n;
    }

    /// Validate the signature threshold input.
    static constexpr auto validateSignatureThreshold(uint32_t n, uint32_t t)
        -> uint32_t
    {
        if ((t < 1) || (t > n))
        {
            throw std::invalid_argument("Invalid signature threshold.");
        }
        return t;
    }

    /// Automatically select a key sharing algorithm based on the number of key
    /// shares and the required signature threshold. Prefer the direct method
    /// if t == n.
    static constexpr auto autoSelectAlgorithm(uint32_t n, uint32_t t)
        -> KeySharingAlgorithm
    {
        if (t == n)
        {
            return KeySharingAlgorithm::Direct;
        }
        return KeySharingAlgorithm::ShamirSecretSharing;
    }

    /// Validate the key sharing algorithm input.
    static constexpr auto
    validateAlgorithmSelection(uint32_t n, uint32_t t, KeySharingAlgorithm a)
        -> KeySharingAlgorithm
    {
        if ((t != n) && (a == KeySharingAlgorithm::Direct))
        {
            throw std::invalid_argument("Invalid key sharing algorithm.");
        }
        return a;
    }

  public:
    /// @brief Create a dealer object for managing threshold operations.
    /// @param n The number of key splits.
    /// @param t The threshold required for a valid signature.
    /// @note Auto select direct key split if t == n, otherwise use Shamir
    /// secret sharing.
    constexpr Dealer(uint32_t n, uint32_t t)
        : num_keys_{validateNumKeyShares(n)},
          sig_threshold_{validateSignatureThreshold(n, t)},
          algorithm_{autoSelectAlgorithm(n, t)}
    {
    }

    /// @brief Create a dealer object for managing threshold operations.
    /// @param n The number of key splits.
    /// @note Uses direct key split, i.e., sets t = n.
    constexpr Dealer(uint32_t n)
        : num_keys_{validateNumKeyShares(n)},
          sig_threshold_{n},
          algorithm_{KeySharingAlgorithm::Direct}
    {
    }

    /// @brief Create a dealer object for managing threshold operations.
    /// @param n The number of key splits.
    /// @param t The threshold required for a valid signature.
    /// @param method Specify key sharing algorithm.
    /// @note This constructor is made available soley for the scenario that the
    /// user wants to force use of the Shamir Secret Sharing algorithm when t ==
    /// n.
    constexpr Dealer(uint32_t n, uint32_t t, KeySharingAlgorithm method)
        : num_keys_{validateNumKeyShares(n)},
          sig_threshold_{validateSignatureThreshold(n, t)},
          algorithm_{validateAlgorithmSelection(n, t, method)}
    {
    }

    /// @brief Generate a set of n key shares and the base public key.
    [[nodiscard]] auto generate() const
        -> std::pair<PublicKey, std::vector<KeyShare>>;

    /// @brief Split a root seed into n sub-keys and the base public key.
    /// @details The root seed is first expanded into a BIP32-Ed25519 root key
    /// which is then split. Generated key shares are not guaranteed to be
    /// clamped and thus may not be suitable for dual use as X25519 keys.
    [[nodiscard]] auto splitSeed(std::span<const uint8_t, SEED_SIZE> seed) const
        -> std::pair<PublicKey, std::vector<KeyShare>>;

    /// @brief Split a root key into n sub-keys and the base public key.
    /// @details Split a BIP32-Ed25519 root key into n sub-key shares. Generated
    /// key shares are not guaranteed to be clamped and thus may not be suitable
    /// for dual use as X25519 keys.
    [[nodiscard]] auto splitRootKey(const PrivateKey& root) const
        -> std::pair<PublicKey, std::vector<KeyShare>>;

    /// @brief Create the composite public key from the private key shares.
    [[nodiscard]] auto compositeKey(std::span<const KeyShare> key_shares) const
        -> PublicKey;

    /// @brief Create the composite public key from the public key shares.
    /// @note This will only work when using the Direc key splitting algorighm
    /// and will not work if using Shamir Secret Sharing. Throws an exception if
    /// used improperly.
    [[nodiscard]] auto compositeKey(std::span<const PublicKey> key_shares) const
        -> PublicKey;

    /// @brief Create the composite signing key from the signing key shares.
    /// @note This method is used mostly for testing.
    [[nodiscard]] auto compositeSigningKey(
        std::span<const KeyShare> key_shares
    ) const -> PrivateKey;

    /// @brief Aggregate signature commitment shares.
    /// @details Compute R = R_0 + ... + R_n
    [[nodiscard]] auto aggregateCommitmentShares(
        const std::vector<std::array<uint8_t, COMMITMENT_SIZE>>& commitments
    ) const -> std::array<uint8_t, COMMITMENT_SIZE>;

    /// @brief Compute the coefficients for Lagrange interpolation.
    /// @param key_ids The key IDs (x-coordinates). The key IDs must all be
    /// unique values.
    /// @return Vector of coefficients for each key share (corresponding to the
    /// same order of the key IDs) as big integers packed into 32 byte arrays.
    [[nodiscard]] auto computeLagrangeCoefficients(
        std::span<const uint64_t> key_ids
    ) const -> std::vector<std::array<uint8_t, 32>>;

    /// @brief Aggregate the signature shares into the combined signature.
    [[nodiscard]] auto aggregateSignatureShares(
        const std::vector<std::array<uint8_t, SIGNATURE_SIZE>>& signatures
    ) const -> std::array<uint8_t, SIGNATURE_SIZE>;

    /// @brief Verify a combined Ed25519 signature.
    [[nodiscard]] auto verifySignature(
        std::span<const uint8_t> msg,
        std::span<const uint8_t, SIGNATURE_SIZE> sig,
        const PublicKey& pk
    ) const -> bool;

    /// Accessor for the signature threshold.
    [[nodiscard]] auto thresholdSize() const -> uint32_t
    {
        return sig_threshold_;
    }

    /// Accessor for the number of key shares.
    [[nodiscard]] auto keySharesSize() const -> uint32_t { return num_keys_; }
};

/// @brief Perform signature functions for threshold signature schemes.
struct Signer
{
    /// @brief Compute the signature commitment share when provided the random
    /// nonce.
    /// @details Given the signature nonce r_i (random) compute the commitment
    /// R_i = r_i*B where B is the Ed25519 basepoint.
    /// @param nonce The random nonce (big integer) provided as a 32/64-byte
    /// span.
    /// @return A std::pair of 32-byte std::array objects containing signature
    /// commitment share and random secret nonce in that order.
    /// @note If the provided nonce is 64-bytes it will be returned as a 32-byte
    /// big integer modulo the ed25519 group order.
    [[nodiscard]] static auto
    commitmentShareFromNonce(std::span<const uint8_t> nonce) -> std::pair<
        std::array<uint8_t, COMMITMENT_SIZE>,
        std::array<uint8_t, NONCE_SIZE>>;

    /// @brief Compute the signature commitment share and random nonce.
    /// @details Generate a random nonce r_i then compute the commitment R_i =
    /// r_i*B where B is the Ed25519 basepoint.
    /// @return A std::pair of 32-byte std::array objects containing signature
    /// commitment share and random secret nonce in that order.
    [[nodiscard]] static auto commitmentShareAndNonce() -> std::pair<
        std::array<uint8_t, COMMITMENT_SIZE>,
        std::array<uint8_t, NONCE_SIZE>>;

    /// @brief Compute the signature commitment share and random nonce.
    /// @details Compute the signature nonce r_i (random) and the commitment R_i
    /// = r_i*B where B is the Ed25519 basepoint. The message and signing key
    /// are used to generate the nonce for consistency with RFC8032; however,
    /// additional entropy is included to ensure the nonce is unique.
    /// @param msg The message (bytes) to sign.
    /// @param sk The signing key share.
    /// @return A std::pair of 32-byte std::array objects containing signature
    /// commitment share and random secret nonce in that order.
    [[nodiscard]] static auto
    commitmentShareAndNonce(std::span<const uint8_t> msg, const KeyShare& sk)
        -> std::pair<
            std::array<uint8_t, COMMITMENT_SIZE>,
            std::array<uint8_t, NONCE_SIZE>>;

    /// @brief Compute a signature share.
    /// @param msg A span of bytes (uint8_t) representing the message to sign.
    /// @param nonce The random secret signature share nonce (ri).
    /// @param commitment The signature share commitment (R).
    /// @param base_pk The base public key representing the split key.
    /// @param share_sk The secret key share.
    /// @return An Ed25519 signature as a 64 byte array.
    /// @details Create signature share (R,S), where R is pre-computed.
    [[nodiscard]] static auto signatureShare(
        std::span<const uint8_t> msg,
        std::span<const uint8_t, NONCE_SIZE> nonce,
        std::span<const uint8_t, COMMITMENT_SIZE> commitment,
        const PublicKey& base_pk,
        const KeyShare& share_sk
    ) -> std::array<uint8_t, SIGNATURE_SIZE>;

    /// @brief Compute a signature share.
    /// @param msg A span of bytes (uint8_t) representing the message to sign.
    /// @param nonce The random secret signature share nonce (ri).
    /// @param commitment The signature share commitment (R).
    /// @param coefficient The lagrange coefficient.
    /// @param base_pk The base public key representing the split key.
    /// @param share_sk The secret key share.
    /// @return An Ed25519 signature as a 64 byte array.
    /// @details Create signature share (R,S), where R is pre-computed.
    [[nodiscard]] static auto signatureShare(
        std::span<const uint8_t> msg,
        std::span<const uint8_t, NONCE_SIZE> nonce,
        std::span<const uint8_t, COMMITMENT_SIZE> commitment,
        std::span<const uint8_t, COEFFICIENT_SIZE> coefficient,
        const PublicKey& base_pk,
        const KeyShare& share_sk
    ) -> std::array<uint8_t, SIGNATURE_SIZE>;

    [[nodiscard]] static auto verifySignature(
        std::span<const uint8_t> msg,
        std::span<const uint8_t, SIGNATURE_SIZE> sig,
        const PublicKey& pk
    ) -> bool;
};

/// @brief Perform signature functions for threshold signature schemes.
/// @details Threshold signatures are a multi-step process, so we use a signer
/// object that can store state. The signer takes the starting state (message,
/// key share, etc.) and then computes the nonce and commitment, which are
/// stored for later use. Once an aggragate commitment is obtained from the
/// dealer, the signature share may be generated. Finally, the aggregate
/// signature may be verified when received from the dealer.
class StatefulSigner
{
  private:
    std::vector<uint8_t> msg_;
    SecureByteArray<COEFFICIENT_SIZE> langrange_coeff_{};
    SecureByteArray<NONCE_SIZE> nonce_{};
    PublicKey agg_vkey_;
    KeyShare key_share_;

  public:
    /// @brief Construct a new stateful signer object.
    /// @param msg The message (bytes) to sign.
    /// @param vkey The aggregate verification key.
    /// @param key The signing key share.
    StatefulSigner(
        std::span<const uint8_t> msg,
        const PublicKey& vkey,
        KeyShare key
    )
        : agg_vkey_{vkey}, key_share_{std::move(key)}
    {
        msg_.reserve(msg.size());
        std::copy_n(msg.begin(), msg.size(), std::back_inserter(msg_));
        langrange_coeff_[0] = 1;  // default Lagrange coef to 1
    }

    /// @brief Construct a new stateful signer object.
    /// @param msg The message (bytes) to sign.
    /// @param vkey The aggregate verification key.
    /// @param key The signing key share.
    /// @param coef The Lagrange coefficient as a packed 32-byte integer.
    StatefulSigner(
        std::span<const uint8_t> msg,
        const PublicKey& vkey,
        KeyShare key,
        std::span<const uint8_t, COEFFICIENT_SIZE> coef
    )
        : agg_vkey_{vkey}, key_share_{std::move(key)}
    {
        msg_.reserve(msg.size());
        std::copy_n(msg.begin(), msg.size(), std::back_inserter(msg_));
        std::copy_n(coef.begin(), COEFFICIENT_SIZE, langrange_coeff_.begin());
    }

    /// @brief Generate a commitment share.
    /// @details Generate a commitment share from a random nonce. The nonce is
    /// stored for later use when creating a signature share. The commitment
    /// share may be shared with a dealer for aggregation.
    [[nodiscard]] auto commitmentShare()
        -> std::array<uint8_t, COMMITMENT_SIZE>;

    /// @brief Generate a signature share.
    /// @param agg_commitment The aggregate signature commitment.
    [[nodiscard]] auto signatureShare(
        std::span<const uint8_t, COMMITMENT_SIZE> agg_commitment
    ) const -> std::array<uint8_t, SIGNATURE_SIZE>;

    /// @brief Generate a signature share.
    /// @param agg_commitment The aggregate signature commitment.
    /// @param langrange_coeff The Lagrange coefficient.
    [[nodiscard]] auto signatureShare(
        std::span<const uint8_t, COMMITMENT_SIZE> agg_commitment,
        std::span<const uint8_t, COEFFICIENT_SIZE> langrange_coeff
    ) const -> std::array<uint8_t, SIGNATURE_SIZE>;

    /// @brief Verify an aggregate signature returned by the dealer.
    [[nodiscard]] auto verifySignature(
        std::span<const uint8_t, SIGNATURE_SIZE> sig
    ) const -> bool;
};

}  // namespace cardano::tss

#endif  // _CARDANO_TSS_HPP_
